sample_app/config/routes.rb
Rails.application.routes.draw do
  
  
  root 'static_pages#application'
  
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get  '/login', to:'sessions#new'
  post  '/login', to:'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get  '/newMeeting',    to: 'meetings#new'
  post '/newMeeting', to:'meetings#create'

  resources :users
  resources :meetings
end

sample_app/app/models/meeting.rb
class Meeting < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true, length: {maximum:255}
    validates :startTime, presence: true
    validates :endTime, presence: true

    validate :valid_meeting_time

def valid_meeting_time 
    if startTime > endTime
      errors.add(:Time, 'Invalid meeting time')
    end
end

end

sample_app/app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    validates :name, presence: true, length: {maximum:50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:255},format: { with: VALID_EMAIL_REGEX},uniqueness: {case_sensitive:false}
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    include UsersHelper
end

sample_app/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
      def new
      @meeting = Meeting.new 
  
    end
  
    def index
        @meetings = Meeting.all
    end
  
    def show
      @meeting = Meeting.find(params[:id])
    end
  
    def create
      @meeting = Meeting.new(meeting_params)
      if @meeting.save
        log_in @meeting
        flash[:success] = "New meeting has been created!"
        redirect_to @meeting
      else
        render 'new'
      end
    end
  
    def edit 
      @meeting = Meeting.find(params[:id])
    end
  
    def update 
      @meeting = Meeting.find(params[:id])
      if @meeting.update_attributes(meeting_params)
        flash[:success] = "Meeting updated"
        redirect_to meetings_path
      else  
        render 'edit'
      end
    end 
  
    def destroy
      Meeting.find(params[:id]).destroy
      flash[:success] = "Meeting deleted successfully...!"
      redirect_to meetings_path
    end
  
    private
  
    def meeting_params
      params.require(:meeting).permit(:title, :description, :startTime, :endTime, :isActive)
    end

    def current_user_loggedin
        if(session[:user_id])
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
  
  end
  

sample_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if(user && user.authenticate(params[:session][:password]))
      log_in(user)
      redirect_to user
    else
      flash.now[:danger]="Invalid Email/Password"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact 
  end
end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def new
    @user = User.new    
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else  
      render 'edit'
    end
  end 

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted successfully...!"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please Login to continue...!"
      redirect_to login_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title='')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end

    def allmeetings
        @meetings = Meeting.all
    end
end

sample_app/app/helpers/meetings_helper.rb
module MeetingsHelper
     
end

sample_app/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if(session[:user_id])
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def current_user?(user)
        user == current_user
    end
    
    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user= nil
    end
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app/app/helpers/users_helper.rb
module UsersHelper

    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.github.com/jaripog">JARIPOG</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Dashboard", meetings_path %></li>
          <li><%= link_to "Users", users_path %></li>
           <% if current_user.admin? %>
                  <li><%= link_to "New meeting", newMeeting_path %></li>
            <%end%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>      </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

sample_app/app/views/layouts/_rails_default.html.erb
 <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

sample_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% if logged_in?%>
      <% @allmeetings = allmeetings%>
        <% @allmeetings.each do |meeting| %> 
        <% if ((meeting.startTime - Time.now)/1.minute <=15 && meeting.isActive == true )%>
              <script> alert('You have a meeting uphead title:<%= meeting.title%>') </script>
        <%end%>
      <%end%>
    <%end%>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

sample_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div> 
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

sample_app/app/views/shared/_error_messages_meetings.html.erb
<% if @meeting.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@meeting.errors.count, "error") %>.
        </div> 
        <ul>
            <% @meeting.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

sample_app/app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<p>
    The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
    Tutorial</em></a> is a
    <a href="https://www.railstutorial.org/book">book</a> and
    <a href="http://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
    <a href="http://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample application for the tutorial.
</p>

sample_app/app/views/static_pages/application.html.erb
<% provide(:title, "Home")%>

    <div class="center jumbotron">
      <h1>Welcome to the Sample App</h1>
      <h2>
        This is the home page for the
        <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
      </h2>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
    <%= link_to image_tag("rails.png", alt: "Rails logo"),'http://rubyonrails.org/' %>

sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

sample_app/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="https://www.railstutorial.org/help">Rails Tutorial help page</a>.
    To get help on this sample app, see the
    <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

sample_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name,class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email,class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password,class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation,class: 'form-control' %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

sample_app/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save Changes') %>
<h1>update your profile</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form'%>
    </div>
</div>

sample_app/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %> |
        <%= link_to "delete", user, method: :delete,data: { confirm: "You sure?" } %>
      <%end%>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

sample_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create My Account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form'%>
  </div>
</div>

sample_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>